### ISSUE TITLE
How to deal with MeCab errors?

### ISSUE THREAD

**Issue by lemuriandezapada** [polm/fugashi#89] opened 2024-03-24 08:05 UTC
Unfortunately MeCab has a bunch of errors, that spill into fugashi.
For example the 帰る in 家に帰る gets lemmatized as 返る even when originally written in kanji

**Comment by polm** [comment] 2024-03-24 08:10
There's not a single generic way to deal with errors, it depends on the details of the error. 

That said, I can't imagine 帰る being lemmatized as 返る in any situation. Can you give example code that shows the error and the version of fugashi and any dictionaries you're using?

**Comment by lemuriandezapada** [comment] 2024-03-24 09:38
That's what I thought as well

Under fugashi 1.3.0 and just the default unicode dictionary the following code reproduces the issue above (plus a separate issue that concatenates some PoS to the lemma)

`from fugashi import Tagger
#tagger = Tagger('-Owakati')
tags = tagger("私は家に帰る")
for tag in tags:
    print(tag.surface, tag.feature.lemma)`
    
   and outputs 
   `私 私-代名詞
は は
家 家
に に
帰る 返る`

**Comment by polm** [comment] 2024-03-24 09:49
I assume by the "default unidic dictionary" you mean unidic-lite. 

I was able to reproduce this. Apparently the UniDic authors consider 帰る and 返る similar enough that they are treated as orthographic variation, so this is not a bug. (The 代名詞 thing is also weird but again, that's just what they do.)

You might want to use the `orthBase` feature instead of `lemma` - it seems to be closer to what you expect.

If you want to override situations like this, you can make your own custom dictionary. You'll need to see the MeCab docs for how to do that.

Since this is an issue with the design of UniDic, which I don't have control over, I'll close it.

**Closed by polm** 2024-03-24 09:49 UTC

**Comment by lemuriandezapada** [comment] 2024-03-24 10:09
thanks 
I'll try to see what hack I can come up with
